// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-interest-registrations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_interest_registrations_default = defineTool({
  name: "list_my_interest_registrations",
  title: "List my interest registrations",
  description: "List Sacred Care interest registrations submitted by the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("interest_registrations").select("id, first_name, email, cemetery, services, created_at").order("created_at", { ascending: false });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: (data ?? []).length === 0 ? "You have no interest registrations yet." : JSON.stringify(data, null, 2)
        }
      ],
      structuredContent: { registrations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-interest-registration.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient2(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_interest_registration_default = defineTool2({
  name: "create_interest_registration",
  title: "Register interest",
  description: "Create a Sacred Care interest registration for the signed-in user. Use this when the caller asks to register interest in Sacred Care's burial care services.",
  inputSchema: {
    first_name: z.string().trim().min(1).max(100).describe("First name of the person registering."),
    cemetery: z.string().trim().min(1).max(200).describe("Cemetery where the loved one is resting."),
    services: z.array(z.string().min(1).max(120)).max(20).optional().describe(
      "Optional list of services the caller is interested in (e.g. 'One-time clean & restore', 'Ongoing care visits')."
    )
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ first_name, cemetery, services }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return {
        content: [
          { type: "text", text: "Your account has no email on file." }
        ],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("interest_registrations").insert({
      user_id: ctx.getUserId(),
      first_name,
      email,
      cemetery,
      services: services ?? []
    }).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Registered interest for ${first_name} at ${cemetery}.`
        }
      ],
      structuredContent: { registration: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qoivpignrgbmuujoragh";
var mcp_default = defineMcp({
  name: "sacred-care-mcp",
  title: "Sacred Care",
  version: "0.1.0",
  instructions: "Tools for Sacred Care, a compassionate burial-care service. Use these to help a signed-in user view and create their interest registrations.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_interest_registrations_default, create_interest_registration_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
